require'settings'
require'plugins'
require'nvim-lsp'
require'colorscheme'
require'nvim-cmp'
require'lline'
require'buffline'
require'colorizer-nvim'
require'autocommands'
require'keymaps'
require'treesitter'

