vim.o.hidden = true
vim.o.wrap = false
vim.o.encoding = "utf-8"
vim.o.pumheight = 10
vim.o.fileencoding = "utf-8"
vim.o.ruler = true
vim.o.cmdheight = 2
vim.o.mouse = "a"
vim.o.conceallevel = 0
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
-- vim.o.smartab = true
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.number = true
vim.o.cursorline = true
vim.o.showtabline = 2
vim.o.backup = false
-- vim.o.writetobackup = false
vim.o.clipboard = "unnamedplus"
vim.o.termguicolors = true
vim.o.scrolloff = 8
vim.o.hlsearch = false
vim.o.swapfile = false
vim.o.incsearch = true
vim.o.scrolloff = 8
