require("plugins.git-signs")
require("plugins.alpha")
require("plugins.impatient")
require("plugins.lsp")
require("plugins.dap")
require("plugins.ui")
require("plugins.null-ls")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.telescope")
require("plugins.indentline")

require("plugins.wichkey")
require("plugins.toggleterm")
require("plugins.nvimtree")
require("plugins.colorizer")
